подключает сервер, описывает класс получения информации
htmlacademy-react/700999-what-to-watch-6 pull request #11
Opened 2021-03-05 20:50 UTC by Makemanback

2021-03-06 12:21 UTC, Shv-sergey70 requested changes

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/api/api.js
> +      throw err;
Тут незачем кидать ошибку, так как через пару строк ниже она же и будет выкинута

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/components/catalog-more/catalog-more.jsx
> +};
В обоих случаях можно использовать короткий синтаксис и опустить `return`

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/components/film/film.prop.js
> +  // rating: PropTypes.shape({
Закоментированного кода быть не должно

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/components/small-card/small-card.jsx
> +const SmallCard = ({id, image, title, _handleHoverCard, _handleHoverOutCard, isVideo}) => {
Пропсы нельзя помечать приватными `_`. Это нелогично что аргумент принимает некую приватную функцию

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/store/api-actions.js
> +    );
Это все удаляем. Такой код тебе не нужен

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/store/api-actions.js
> +    );
Показал на примере `fetchFilmsList`, как можно использовать обычные методы:
```
export default class ApiService {
  constructor() {
    _defineProperty2(this, `checkAuth`, () => (dispatch, _getState, api) =>
      api
        .get(`/login`)
        .then(() =>
          dispatch(ActionCreator.requireAuthorization(AuthorizationStatus.AUTH))
        )
        .catch(() => {})
    );

    _defineProperty2(
        this,
        `login`,
        ({login: email, password}) => (dispatch, _getState, api) =>
          api
          .post(`/login`, {
            email,
            password
          })
          .then(() =>
            dispatch(
                ActionCreator.requireAuthorization(AuthorizationStatus.AUTH)
            )
          )
    );
  }

  fetchFilmsList() {
    return (dispatch, _getState, api) =>
      api
        .get(`/films`)
        .then(({data}) => dispatch(ActionCreator.loadFilms(data)));
  }

  static adaptToClient(film) {

    const adaptedFilm = Object.assign(
        {},
        film,
        {
          image: film.preview_image,
          video: film.preview_video_link,
          title: film.name,
          rating: {
            score: film.rating,
          },
          runTime: film.run_time,
        });

    delete adaptedFilm.preview_image;
    delete adaptedFilm.preview_video_link;
    delete adaptedFilm.name;
    delete adaptedFilm.rating;
    delete adaptedFilm.run_time;

    return adaptedFilm;
  }
}
```

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/store/api-actions.js
> +// );
Комментарии чистим перед мержем в мастер

2021-03-06 12:21 UTC, Shv-sergey70 commented on src/components/cards-list/cards-list.jsx
> +const apiSevice = new ApiService();
`apiService`

2021-03-08 09:22 UTC, Makemanback commented on src/components/catalog-more/catalog-more.jsx
> +};
Не понял как

2021-03-08 09:36 UTC, Makemanback commented on src/components/catalog-more/catalog-more.jsx
> +};
`const mapDispatchToProps = (dispatch) => ({
  onShowMore() {
    dispatch(ActionCreator.showMore())
  }
});`

Так?

2021-03-08 10:52 UTC, Shv-sergey70 commented on src/components/catalog-more/catalog-more.jsx
> +};
Да

2021-03-08 10:55 UTC, merged