Module6 task2
htmlacademy-react/700999-what-to-watch-6 pull request #12
Opened 2021-03-08 11:03 UTC by Makemanback

2021-03-09 16:57 UTC, Shv-sergey70 commented on src/store/reducer.js
> +        genres: [...state.genres, ...action.payload]
А если кто-то еще раз вызовет этот `case`, ты будешь докидывать к уже имеющимся жанрам еще больше? Так не стоит делать

2021-03-09 17:08 UTC, Shv-sergey70 requested changes
__Страницы MyList, Add review доступны только авторизованным пользователям. Если пользователь не авторизован, то при переходе к этим страницам выполняется перенаправление на страницу Sign In.__

Сейчас даже детальная страница просмотра фильма недоступна

2021-03-09 17:08 UTC, Shv-sergey70 commented on src/components/user-block/user-block.jsx
> +  const isSignedIn = authorizationStatus === AuthorizationStatus.AUTH ?
Переменную нельзя именовать с `is`. Обычно такую приставку содержат переменные с булевым типом данных

2021-03-09 17:08 UTC, Shv-sergey70 commented on src/components/user-block/user-block.jsx
> +    </div> :
Для этого можно создать отдельный небольшой компонент

2021-03-12 10:22 UTC, Makemanback commented
При обновлении страницы http://localhost:1347/films/:id падает такая ошибка 
<img width="1094" alt="Screenshot 2021-03-12 at 13 18 40" src="https://user-images.githubusercontent.com/38920557/110926777-dda4c300-8335-11eb-8bf7-895159ed1d6d.png">

в метод ApiService fetchFilm(id) {...} сначала приходит id, а потом undefined, так как метод вызывается два раза неясно почему (вызов метода присутствует только в одном компоненте)

2021-03-12 14:27 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +// import AddReview from '../add-review/add-review';
Если что-то больше не используется - сразу удаляй

2021-03-12 14:27 UTC, Shv-sergey70 commented on src/utils.js
> +};
```
export const timeConvert = (time) => {
  const hours = Math.floor(time / 60);
  const minutes = Math.round(time % 60);
  
  return `${hours}h ${minutes}m`;
};
```

2021-03-12 14:27 UTC, Shv-sergey70 commented on src/store/reducer.js
> +  isFilmLoaded: false
Зачем эти свойства, если ты опираешься на то, пустые ли данные `allFilms`, `currentFilm`?

2021-03-12 14:27 UTC, Shv-sergey70 commented on src/store/reducer.js
> +  currentFilmId: null,
Это нигде не используется. Проверь внимательно весь проект

2021-03-12 14:27 UTC, merged