Module7 task1
htmlacademy-react/700999-what-to-watch-6 pull request #14
Opened 2021-03-19 08:42 UTC by Makemanback

2021-03-19 16:51 UTC, Shv-sergey70 requested changes
1. Весь закомментированный код нужно удалить.
2. Сейчас при создании комментария, либо изменение символа или нажатие на звездочку ведет к перерисовке всей страницы. Такого быть не должно.
3. На детальной странице любое переключение между вкладками 
Overview
Details
Reviews
Ведет к перерисовке всей страницы. Так быть не должно. А главное, это происходит через новый адрес в урле. В ТЗ сказано:
__Приложение состоит из нескольких страниц: Main (/), Sign In (/login), MyList (/mylist), Film (/films/:id), Add review (/films/:id/review), Player (/player/:id).__
Тех что ты сделал - нет

2021-03-19 16:51 UTC, Shv-sergey70 commented on src/components/add-review/add-review.jsx
> +  const {currentFilm} = useSelector(({FILM}) => FILM);
Извлекай всегда строго те свойства, что нужны:
```
const currentFilm = useSelector(({FILM}) => FILM.currentFilm);
```
В твоей реализации, любое изменение свойства в объекте `FILM` приведет к перерисовке компонента. В моем случае - только изменение currentFilm к этому приведет

2021-03-19 16:51 UTC, Shv-sergey70 commented on src/components/add-review/add-review.jsx
> +  const {currentFilm} = useSelector(({FILM}) => FILM);
Так нужно поправить везде

2021-03-19 16:51 UTC, Shv-sergey70 commented on src/components/add-review/add-review.jsx
> +    // dispatch(apiService.pushComment(commentData));
Если код не используется - всегда сразу удаляй его

2021-03-19 20:03 UTC, Shv-sergey70 commented
Переключение между табами по-прежнему ведет к перерисовке многих независимых компонентов на странице

2021-03-22 14:55 UTC, Shv-sergey70 requested changes

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +            return <Player path={path} filmId={filmId} />;
Зачем передаются пропсы в плеер, если они нигде не используются?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/app/app.jsx
> +            const filmId = +match.params.id;
Вместо этой записи, попробуй в самом компоненте использовать хук:
https://reactrouter.com/web/api/Hooks/useparams

То же самое для компонента AddReview

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/app/app.jsx
>  // import MyList from '../my-list/my-list';
Закомментированного кода быть не должно

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/cards-list/cards-list.jsx
> +//     });
Закомментированного кода быть не должно

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-card/film-card.jsx
> +  />;
Вместо немедленногой отрисовки этих компонентов - сделай условную, через switch/case

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-card/film-card.jsx
> +  const [activeTab, setActiveTab] = useState(movieOverview);
Не нужно в стейте хранить компонент целиком

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +  const {authorizationStatus} = useSelector(({USER}) => USER);
Извлекай только то что нужно

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +  const film = currentFilm;
Это зачем?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +  const filteredFilms = useSelector(({ALL_FILMS}) => ALL_FILMS.filteredFilms);
Так как мы на этапе оптимизации - то это нужно тоже оптимизировать.Не нужно больше хранить в стейте фильтрованные фильмы. Используй reselect

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +  const {authorizationStatus} = useSelector(({USER}) => USER);
Зачем доставать это значение здесь, если оно используется только в компонентах двумя уровнями ниже?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +  const filmsToShow = useSelector(({ALL_FILMS}) => ALL_FILMS.filmsToShow);
Это тоже можно извлекать не здесь

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +      loadFilmsData(filmId);
Зачем в `loadFilmsData` передавать параметр, если она его не принимает?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +    .slice(0, 4);
Это все может уйти в логику reselect селектора

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +      poster={poster}
Почему это передано в деструктурированном виде? Почему просто не передать весь объект фильма?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-container/film-container.jsx
> +const FilmContainer = ({filmId}) => {
Что-то я стал сомневаться что тебе этот компонент вообще нужен. Зачем он? Ты следуешь какому-то паттерну?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/app/app.jsx
>          {/* <PrivateRoute exact path={Path.MY_LIST}>
Закомментированного кода быть не должно

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-nav/film-nav.jsx
> +  const {FILMS} = Path;
Зачем делать деструктуризацию ради одного свойства?

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/film-nav/film-nav.jsx
> +  activeTab: PropTypes.object.isRequired,
Посмотри как можно более детально описать пропс, чтобы сказать что там react-компонент

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/genres-list/genres-list.jsx
> +  const {genres} = useSelector(({GENRES}) => GENRES);
Доставай только то что нужно. Проверь везде что делаешь так

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/movie-card/movie-card.jsx
> +  const {authorizationStatus} = useSelector(({USER}) => USER);
То же что и выше

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/private-route/private-route.jsx
> +  const {authorizationStatus} = useSelector(({USER}) => USER);
То же что и выше

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/components/sign-in/sign-in.jsx
> +  const {authorizationStatus} = useSelector(({USER}) => USER);
То же что и выше

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/store/action.js
> +  return {
Используй короткий синтаксис здесь и везде в аналогичных случаях, без return

2021-03-22 14:55 UTC, Shv-sergey70 commented on src/const.js
>    MOVIE_REVIEWS: `/films/:id/reviews`,
Это актуальные пути?

2021-03-22 15:22 UTC, Makemanback commented on src/components/app/app.jsx
> +            return <Player path={path} filmId={filmId} />;
Это подготовка к следующему заданию

2021-03-24 19:51 UTC, merged